// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AceptacionTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() throws MalformedURLException {
    driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), DesiredCapabilities.chrome());
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void aceptacion() {
    driver.get("http://host.docker.internal:8181/contactos");
    driver.manage().window().setSize(new Dimension(1534, 814));
    driver.findElement(By.cssSelector(".text-right > .btn")).click();
    driver.findElement(By.id("id")).sendKeys("0");
    driver.findElement(By.id("nombre")).click();
    driver.findElement(By.id("nombre")).sendKeys("111111");
    driver.findElement(By.id("btnEnviar")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) .container .btn")).getText(), is("Sr. 111111"));
    driver.findElement(By.cssSelector("tr:nth-child(1) .container .btn")).click();
    assertThat(driver.findElement(By.cssSelector("h4")).getText(), is("Sr. 111111"));
    driver.findElement(By.cssSelector(".btn:nth-child(4)")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("tr:nth-child(1) .btn-success > .fas"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector("tr:nth-child(1) .btn-success > .fas")).click();
    driver.findElement(By.id("apellidos")).click();
    driver.findElement(By.id("apellidos")).sendKeys("11111");
    driver.findElement(By.id("btnEnviar")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) .container .btn")).getText(), is("Sr. 111111 11111"));
    driver.findElement(By.cssSelector("tr:nth-child(1) .far")).click();
    assertThat(driver.switchTo().alert().getText(), is("¿Estas seguro?"));
    driver.switchTo().alert().dismiss();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) .container .btn")).getText(), is("Sr. 111111 11111"));
    driver.findElement(By.cssSelector("tr:nth-child(1) .far")).click();
    assertThat(driver.switchTo().alert().getText(), is("¿Estas seguro?"));
    driver.switchTo().alert().accept();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) .container .btn")).getText(), is("Dr. Adolf Dunster"));
  }
}
